exam_network/urls.py
from django.urls import path
from . import views

app_name = 'exam_network'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('welcome/', views.welcome, name='welcome'),
    path('add_course/', views.add_course, name='add_course'),
    path('add_students/', views.add_students, name='add_students'),
    path('add_exam/', views.add_exam, name='add_exam'),
    path('about_us/', views.about_us, name='about_us'),
    path('contact/', views.contact, name='contact'),
    path('exam_result/', views.exam_result, name='exam_result'),
    path('help/', views.help, name='help'),
    path('account/', views.account, name='account'),
    path('exams/', views.exams, name='exams'),
    path('exams/<id>', views.exams, name='exams'),
    path('exams/remove/<id>', views.exam_remove, name='exam_remove'),
    path('exams/edit/<id>', views.exam_edit, name='exam_edit'),
]

wad2_ae1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exam_network.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam_network/forms.py
from django import forms
from django.contrib.auth.models import User
import datetime
from exam_network.models import Profile, Course, Question, Exam, Answer, Submission


class UserForm(forms.ModelForm):
    first_name = forms.CharField(required=True, label_suffix='', widget=forms.TextInput(
        attrs={"class": "input_row", "placeholder": "Enter First Name"}))
    last_name = forms.CharField(required=True, label_suffix='', widget=forms.TextInput(
        attrs={"class": "input_row", "placeholder": "Enter Last Name"}))
    email = forms.EmailField(required=True, label_suffix='', widget=forms.TextInput(
        attrs={"class": "input_row", "placeholder": "Enter Email"}))
    password = forms.CharField(required=True, label_suffix='', widget=forms.PasswordInput(
        attrs={"class": "input_row", "placeholder": "Enter Password"}))
    confirm_password = forms.CharField(required=True, label_suffix='', widget=forms.PasswordInput(
        attrs={"class": "input_row", "placeholder": "Re-enter Password"}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password',)

    def clean_password(self):
        password = self.cleaned_data.get("password")
        if len(password) < 8:
            raise forms.ValidationError(
                ('Password too short.'),
                code='invalid_password_len',
            )
        return password

    def clean_conform_password(self):
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("conform_password")
        if password1 != password2:
            raise forms.ValidationError(
                ('Password mismatch.'),
                code='password_mismatch',
            )
        return password2

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).count() != 0:
            raise forms.ValidationError(
                ("This email is already in use."),
                code='email_in_use',
            )
        return email


class ProfileForm(forms.ModelForm):
    ROLES = [('S', 'Student'), ('T', 'Teacher')]
    role = forms.ChoiceField(label_suffix='', choices=ROLES, widget=forms.RadioSelect)

    class Meta:
        model = Profile
        fields = ('role',)

    def clean_role(self):
        role = self.cleaned_data.get('role')
        if role != 'S' and role != 'T':
            raise forms.ValidationError(
                ("Invalid role."),
                code='invalid_role',
            )
        return role


class CourseForm(forms.ModelForm):
    name = forms.CharField(label_suffix='', required=True, widget=forms.TextInput(
        attrs={"class": "", "placeholder": "Enter Course Name."}))
    description = forms.CharField(label_suffix='', required=True, widget=forms.TextInput(
        attrs={"class": "", "placeholder": "Enter Course Description."}))

    class Meta:
        model = Course
        fields = ('name', 'description')

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if Course.objects.filter(name=name).count() != 0:
            raise forms.ValidationError(
                ("Course already exists."),
                code='course_exists',
            )
        return name


class ExamForm(forms.ModelForm):
    title = forms.CharField(label_suffix='', required=True, widget=forms.TextInput(
        attrs={"class": "", "placeholder": "Enter Exam Name"}))
    date_available = forms.DateTimeField(
        label_suffix='',
        required=True,
        label="Date Available",
        widget=forms.SplitDateTimeWidget)
    deadline = forms.DateTimeField(
        label_suffix='',
        required=True,
        label="Deadline",
        widget=forms.SplitDateTimeWidget)

    class Meta:
        model = Exam
        fields = ('title', 'date_available', 'deadline')

    def clean_date_available(self):
        now = datetime.datetime.now()
        date_available = self.cleaned_data.get('date_available')
        if date_available < now:
            raise forms.ValidationError(
                ("Date available must be in future."),
                code='past_date_available',
            )
        return date_available

    def clean_deadline(self):
        now = datetime.datetime.now()
        date_available = self.cleaned_data.get('date_available')
        deadline = self.cleaned_data.get('deadline')
        if deadline < now:
            raise forms.ValidationError(
                ("Deadline must be in future."),
                code='past_deadline',
            )
        elif deadline < date_available:
            raise forms.ValidationError(
                ("Date must be in future."),
                code='past_date',
            )
        return deadline


class QuestionForm(forms.ModelForm):
    content = forms.CharField(label_suffix='', required=True, widget=forms.TextInput(
        attrs={"class": "input_row", "placeholder": "Enter Question."}))
    choice_1 = forms.CharField(label_suffix='', required=True, widget=forms.TextInput(
        attrs={"class": "input_row", "placeholder": "Enter Choice 1."}))
    choice_2 = forms.CharField(label_suffix='', required=True, widget=forms.TextInput(
        attrs={"class": "input_row", "placeholder": "Enter Choice 2."}))
    choice_3 = forms.CharField(label_suffix='', required=True, widget=forms.TextInput(
        attrs={"class": "input_row", "placeholder": "Enter Choice 3."}))
    choice_4 = forms.CharField(label_suffix='', required=True, widget=forms.TextInput(
        attrs={"class": "input_row", "placeholder": "Enter Choice 4."}))
    choice_5 = forms.CharField(label_suffix='', required=True, widget=forms.TextInput(
        attrs={"class": "input_row", "placeholder": "Enter Choice 5."}))
    ANSWER = [(i, str(i)) for i in range(1, 6)]
    correct_answer = forms.ChoiceField(label_suffix='', required=True, choices=ANSWER)

    class Meta:
        model = Question
        fields = (
            'content',
            'choice_1', 'choice_2', 'choice_3', 'choice_4', 'choice_5',
            'correct_answer'
        )

exam_network/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.urls import reverse
from .models import Exam, Course, Question, Submission, Answer
from django.contrib.auth.models import User
from django.db.models import Q
import datetime
from django.utils.timezone import make_aware
import json


def error(request, message, error):
    return render(request, 'exam_network/error.html', status=error, context={"message": message, "error": error})


def index(request):
    return render(request, 'exam_network/index.html', {})


def process_account_edit(request, return_url_name, create):
    first_name = request.POST.get("first_name")
    last_name = request.POST.get("last_name")
    email = request.POST.get("email")
    username = request.POST.get("email")
    role = request.POST.get("role")
    password = request.POST.get("password")
    confirm_password = request.POST.get("confirm_password")

    # checks
    if password != confirm_password:
        return error(request, "the passwords do not match", 403)
    if password == None or password.strip() == "":
        return error(request, "the password is empty", 403)
    if role != "S" and role != "T":
        return error(request, "the role is invalid", 403)
    if role != "S" and role != "T":
        return error(request, "the role is invalid", 403)
    if email == None or email.strip() == "":
        return error(request, "the email is empty", 403)
    if last_name == None or last_name.strip() == "":
        return error(request, "the surname is empty", 403)
    if first_name == None or first_name.strip() == "":
        return error(request, "the name is empty", 403)

    # passed checks
    user = None
    if create:
        try:
            User.objects.get(username=username)  # check if this user exists
            return error(request, "this email is already taken", 403)
        except:
            # doesnt exist so create
            user = User.objects.create(username=username)
    else:
        try:
            # check if this user exists
            user = User.objects.get(username=username)
        except:
            return error(request, "this account does not exist", 403)

    user.first_name = first_name
    user.last_name = last_name
    user.email = email
    if password != "***********":
        user.set_password(password)
    user.profile.role = role
    user.save()
    login(request, user)
    return redirect(reverse('exam_network:' + return_url_name))


def get_courses(request):
    if not request.user.is_authenticated:
        return Course.objects.none()
    if request.user.profile.role == "S":
        return Course.objects.filter(students__in=[request.user])
    elif request.user.profile.role == "T":
        return Course.objects.filter(teacher=request.user)
    else:
        return Course.objects.none()


def get_exams(request, courses):
    if not request.user.is_authenticated:
        return Exam.objects.none()
    if request.user.profile.role == "T":
        return Exam.objects.filter(course__in=courses).order_by("date_available")

    # else return for students
    now = datetime.datetime.now()
    # Titles of exams the Student has submissions for
    student_submissions = Submission.objects.filter(
        student=request.user).values_list('exam__title')
    # Exams the Student has submissions for
    student_submissions = Exam.objects.filter(
        course__in=courses, title__in=student_submissions)
    # Student's upcoming exams
    student_upcoming = Exam.objects.filter(
        course__in=courses, deadline__gte=now)
    # OR operator combines two queries into either submitted or upcoming exams
    return (student_submissions | student_upcoming).order_by("date_available")


def signup(request):
    if request.user.is_authenticated:
        return error(request, "you are already logged in", 403)
    elif request.method == "POST":
        return process_account_edit(request, 'welcome', True)
    else:
        return render(request, 'exam_network/signup.html')


def user_login(request):
    if request.user.is_authenticated:
        return error(request, "you are already logged in", 403)
    elif request.method == 'POST':
        username = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('exam_network:index'))
            return HttpResponse("Your Exam Network account is disabled.")
        print(f'Invalid login details: {username}')
        return error(request, "the login details are incorrect", 403)
    else:
        return render(request, 'exam_network/login.html')


def account(request):
    if not request.user.is_authenticated:
        return error(request, "you are not logged in", 403)
    elif request.method == 'POST':
        return process_account_edit(request, 'index', False)
    else:
        return render(request, 'exam_network/account.html')


def contact(request):
    return render(request, 'exam_network/contact.html')


def user_logout(request):
    if not request.user.is_authenticated:
        return error(request, "you are not logged in", 403)
    else:
        logout(request)
        return redirect(reverse('exam_network:index'))


def add_course(request):
    if not request.user.is_authenticated:
        return error(request, "you are not logged in", 403)
    elif request.user.profile.role != "T":
        return error(request, "you do not have permission do perform this operation", 403)
    elif request.method == 'POST':
        # get data
        name = request.POST.get('course_name')
        details = request.POST.get('details')

        # perform checks
        if name == None or name.strip() == "":
            return error(request, "the course name is not filled in", 403)
        if details == None or details.strip() == "":
            return error(request, "the details are not filled in", 403)

        # create new course if successful and if does not exist
        try:
            Course.objects.get(name__eq=name)  # check if already exists
            return error(request, "a course with this name already exists", 403)
        except:
            course = Course.objects.create(
                name=name, description=details, teacher=request.user)
            course.save()
        return redirect(reverse('exam_network:index'))
    else:
        return render(request, 'exam_network/add_course.html')


def add_students(request):
    courses = get_courses(request)

    if request.method == "POST":
        if not request.user.is_authenticated:
            return error(request, "you are not logged in", 403)
        elif request.user.profile.role != "T":
            return error(request, "you do not have permission to add students", 403)
        else:
            try:
                course = courses.get(id=request.POST.get(
                    "course_id"), teacher=request.user)
                students = request.POST.get("students").split(",")
                excluded_students = []
                for student in students:
                    student = student.strip()
                    try:
                        student_object = User.objects.get(email=student)
                        if student_object.profile.role != "S":
                            # gets catched in except
                            raise Exception("user is not a student")
                        if student_object in course.students.all():
                            # gets catched in except
                            raise Exception("user is already in the course")
                        if student_object == course.teacher:
                            # gets catched in except
                            raise Exception("user is a teacher")

                        course.students.add(student_object)
                    except:
                        excluded_students.append(student)

                if len(excluded_students) == len(students):
                    return error(request, "the operation was not successful. None of these students were added: " + ", ".join(excluded_students), 403)
                if len(excluded_students) != 0:
                    return error(request, "the operation was succesfull but these students were not added: " + ", ".join(excluded_students), 0)
                else:
                    return redirect(reverse('exam_network:exams'))
            except:
                return error(request, "you do not have permission to add students into this course", 403)
    else:
        return render(request, 'exam_network/add_students.html', {"courses": get_courses(request)})


def get_datetime(datetime_string):
    result = datetime.datetime.strptime(datetime_string, "%Y-%m-%dT%H:%M")
    # expecting that all the times will be in UTC timezone
    return make_aware(result)


def datetime_str(date):
    return date.strftime("%Y-%m-%dT%H:%M")


def add_exam(request):
    if request.method == "POST":
        courses = get_courses(request)
        if not request.user.is_authenticated:
            return error(request, "you are not logged in", 403)
        elif request.user.profile.role != "T":
            return error(request, "you do not have permission to add exam", 403)
        else:
            try:
                course = courses.get(id=request.POST.get("course_id"))
                title = request.POST.get("title")
                date_available = get_datetime(
                    request.POST.get("date_available"))
                deadline = get_datetime(request.POST.get("deadline"))

                now = make_aware(datetime.datetime.now())
                try:
                    Exam.objects.get(title=title)  # check if exists

templates/exam_network/about_us.html
{% extends "exam_network/two_split.html" %}
{%block two_split_image_source%}/media/team_work_img1_w16.svg{%endblock%}
{%block two_split_content%}
<div id="signup_content_wrapper">
    <h1 class="big_title">About Us</h1>
    <p class="text" style="margin-top: 30px;">Exam Network is an online testing platform designed to be easy to use for students and teachers. In Exam Network, teachers will find an approachable platform where writing, assigning and marking tests takes less time and less resources. Students will find a platform that makes taking and keeping track of assignments is easy and quick. Best of all, results are calculated upon completion and delivered instantly. No more mass marking for teachers and no more anxious waiting for students. </p>
</div>
{%endblock%}

templates/exam_network/account.html
{% extends "exam_network/two_split.html" %}
{%block two_split_image_source%}/media/online_education_img1_w2.svg{%endblock%}
{%block two_split_content%}
<div id="signup_content_wrapper">
    <h1 class="big_title">Your Account</h1>
    <h3 class="medium_title">Edit your account details</h3>
    <form class="two_split_content" method="POST" style="width: 400px;" id="signup_form">
        {%csrf_token%}
        <div class="input_row">
            <span>Name</span>
            <input name="first_name" value="{{user.first_name}}"required>
        </div>
        <div class="input_row">
            <span>Surname</span>
            <input name="last_name" value="{{user.last_name}}" required>
        </div>
        <div class="input_row">
            <span>Email</span>
            <input type="email" name="email" value="{{user.email}}" readonly>
        </div>
        <div class="input_row">
            <span>I am </span>
            <label><input type="radio" name="role" value="S" {%if user.profile.role == "S"%}checked="checked"{%endif%} disabled> student</label>
            <label style="padding-left: 20px;"><input type="radio" name="role" value="T" {%if user.profile.role == "T"%}checked="checked"{%endif%} disabled> teacher</label>
        </div>
        <div class="input_row">
            <span>Change Password</span>
            <input type="password" name="password" value="***********">
        </div>
        <div class="input_row">
            <span>Confirm Password</span>
            <input type="password" name="confirm_password" value="***********">
        </div>
    </form>
    <a href="{%url 'exam_network:index'%}"><button class="gray_button">Cancel</button></a>
    <button type="submit" class="blue_button" style="margin-top: 10px;" form="signup_form">Edit Profile</button>
</div>
{%endblock%}

templates/exam_network/add_course.html
{% extends "exam_network/two_split.html" %}
{%block two_split_image_source%}/media/new_course_img1_w7.svg{%endblock%}
{%block two_split_content%}
<div id="signup_content_wrapper">
    <h1 class="big_title">Add new course</h1>
    <h3 class="medium_title">Please enter the details</h3>
    <form class="two_split_content" method="POST" style="margin-top: 40px;">
        {%csrf_token%}
        <div class="input_row">
            <span>Course Name</span>
            <input name="course_name">
        </div>
        <div class="input_row">
            <span>Description</span>
            <textarea name="details" rows="6" style="resize: none;"></textarea>
        </div>
        <button type="submit" class="blue_button" style="margin-top: 30px; float: right;">Add</button>
    </form>
    <button class="gray_button" style="margin-top: 30px; float: right;" onclick="window.history.back();">Cancel</button>
</div>
{%endblock%}

templates/exam_network/add_students.html
{% extends "exam_network/two_split.html" %}
{%block two_split_image_source%}/media/adding_students_img1_w14.svg{%endblock%}
{%block two_split_content%}
<div id="signup_content_wrapper">
    <h1 class="big_title">Add students to a course</h1>
    <h3 class="medium_title">Please enter the details</h3>
    <form class="two_split_content" method="POST" style="margin-top: 40px;">
        {%csrf_token%}
        <div class="input_row">
            <span>Select Course</span>
            <select name="course_id" required>
                {%for option in courses%}
                    <option value="{{option.id}}">{{option.name}}</option>
                {%endfor%}
            </select>
        </div>
        <div class="input_row">
            <span>Student emails<br>(comma separated)</span>
            <textarea name="students" rows="6" style="resize: none;" required></textarea>
        </div>
        <button type="submit" class="blue_button" style="margin-top: 30px; float: right;">Add</button>
    </form>
    <button class="gray_button" style="margin-top: 30px; float: right;" onclick="window.history.back();">Cancel</button>
</div>
{%endblock%}

templates/exam_network/exam_result.html
{% extends "exam_network/two_split.html" %}
{%block two_split_image_source%}/media/congratulations_img1_w13.svg{%endblock%}
{%block two_split_content%}
<div>
    <h1 class="big_title">Congratulations!</h1>
    <h3 class="medium_title">You have passed the exam with 69%!</h3>
    <div style="margin-top: 250px;">
        <a href="{%url 'exam_network:index'%}"><button class="gray_button">Cancel</button></a>
        <button class="blue_button">Review</button>
    </div>
</div>
{%endblock%}

templates/exam_network/exams.html
{% extends "exam_network/base.html" %}
{% block page_content %}
{% load static %}
{% load exam_templatetags %}
<link rel="stylesheet" type="text/css" href="{% static 'exams/exams.css' %}">
<div id="exams_wrapper">
    <div id="course_navigator">
        {%for course in courses%}
            <a href="{%url 'exam_network:exams' course.id%}"><button class="blue_button {%if current_course == course%}selected{%endif%}">{{course.name}}</button></a>
        {%endfor%}
        <div id="statistics" class="black_border" {%if request.user.profile.role != "S" and not current_course%}style="display:none"{%endif%}>
            {%get_student_performance user current_course as student_performance%}
            <h1>Cummulative Statistics</h1>
            {%if request.user.profile.role == "S"%}
                <div>
                    <h5>Your Performance</h5>
                    <div>
                        <p>Highest Score: </p><span>{{student_performance.0}}%</span><br>
                        <p>Lowest Score: </p><span>{{student_performance.1}}%</span><br>
                        <p>Average: </p><span>{{student_performance.2}}%</span>
                    </div>
                </div>
            {%endif%}
            {%if current_course%}
                {%get_course_performance current_course as course_performance%}
                <div>
                    <h5>Course Performance</h5>
                    <div>
                        <p>Highest Score: </p><span>{{course_performance.0}}%</span><br>
                        <p>Lowest Score: </p><span>{{course_performance.1}}%</span><br>
                        <p>Average: </p><span>{{course_performance.2}}%</span>
                    </div>
                </div>
            {%endif%}
        </div>

        {%if request.user.profile.role == "T" and current_course%}
            <div id="student_list" class="black_border">
                <div>
                    <h1>Students in this course</h1>
                    <span>{{current_course.students.all.count}}</span>
                </div>
                {%for student in current_course.students.all%}
                    <div>
                        <p>{{student.email}}</p>
                        <form method="POST">
                            {%csrf_token%}
                            <input type="hidden" name="user_delete" value="{{student.email}}"><button class="gray_button">X</button>
                        </form>
                    </div>
                {%endfor%}
            </div>
        {%endif%}
    </div>
    <div id="course_explorer">
        {%if exams|length == 0%}
        <p class="text" style="text-align: center;">Looks like there are no exams in {%if current_course%}course {{current_course.name}}{%else%}your courses{%endif%}</p>
        {%endif%}
        {%for exam in exams%}
            {%get_submission request.user exam as submission%}
            <div class="black_border" {%if exam.date_available > now or exam.deadline < now%}style="color:gray;"{%endif%}>
                <h1>{{exam.title}}</h1>
                {% if user_role == "S" %}
                    {%if submission%}
                        <p>Your Result: </p><span>{{submission.percentage}}%</span><br>
                        <p>Your Score: </p><span>{{submission.score}} out of {{submission.max_score}} points</span><br>
                    {%endif%}
                {% endif %}
                <div style="text-align: right;" class="exam_bottom">
                    <span>Open from: <b>{{exam.date_available}}</b></span>
                    <span>Deadline: <b>{{exam.deadline}}</b></span>

                    {% if user_role == "S" %}
                        <a {%if exam.date_available < now%}href="{%url 'exam_network:exams' exam.id%}"{%endif%}>
                            <button class="{%if submission%}gray_button{%else%}blue_button{%endif%}" {%if exam.date_available > now%}style="visibility:hidden;"{%endif%}>{%if submission%}Review{%else%}Start{%endif%}</button>
                        </a>
                    {% elif user_role == "T" %}
                        <a href="{%url 'exam_network:exams' exam.id%}">
                            <button class="blue_button" style="width: 130px;">View</button>
                        </a>
                        <a href="{%url 'exam_network:exam_remove' exam.id%}">
                            <button class="gray_button" style="transform: scale(0.7);">Remove</button>
                        </a>
                        <a href="{%url 'exam_network:exam_edit' exam.id%}">
                            <button class="blue_button" style="width: 130px;">Edit</button>
                        </a>
                    {% endif %}
                </div>
            </div>
        {%endfor%}
    </div>
</div>
{% endblock %}

templates/exam_network/help.html
{% extends "exam_network/base.html" %}
{% block page_content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'help/help.css' %}">

<h1 id="help_title">We are here to help you. <br />Below we have answered some frequently asked questions. <br /></h1>
<div id="help_content">
    <div class="black_border">
        <h1>Question: I'm a teacher, how do I add a new course?</h1>
        <p class="text">The good news is this part is really easy. Just log in, click Add Course in the navigation bar at the top (it's underneath the Exam Networl logo!), give your course a name and short description and click "Add".</p>
    </div>
    <div class="black_border">
        <h1>Question: I'm a teacher, how do I add students to my course?</h1>
        <p class="text">When you've created your exciting course, if you head to Add Students on the navigation bar, you simply select your course from the dropdown menu (click the little arrow at the right of Select Course). Then you just need to type in the email addresses of the students you wish to add. Be sure to seperate each email address with a comma!.</p>
    </div>
    <div class="black_border">
        <h1>Question: I'm a teacher, how do I set an exam for my students?</h1>
        <p class="text">There's a few steps to this part. <br /> First, click Add Exam in the navigation bar. <br /> Next, select the course you're writing the exam for from the dropdown menu, like you did when adding your students. <br />Now, give your exam a Title by typing it in text box. <br />Now you need to set the time students will be able to sit the exam. Click the little calendar icon in the Date Available Box, and you'll be able to select a date from the calendar and a time. Do the same for the deadline<br />Now you click the blue button with the "+" symbol to start adding questions. <br>Type the question itself in the content box and give one of five potential answers in the answer box. Make sure to click the round button next to the correct answer. <br />Repeat that for as many questions as you'd like to add. <br />Finally, if you're happy with what you've got click the blue "Add" button at the bottom and you're done!<br />If you change your mind at any point you can click the grey "Cancel" button to clear everything out and start again.</p>
    </div>
    <div class="black_border">
        <h1>Question: I'm a student, how do I find my exams?</h1>
        <p class="text">When you've signed up for Exam Network it's up to your teacher to add you to your classes. Once that's been done, you just need to click Exams in the navigation bar at the top, click on your course, and click the exam you want to sit.</p>
    </div>
    <div class="black_border">
        <h1>Question: I'm a student, what will it look like when I sit an exam?</h1>
        <p class="text">Exams are multiple choice. When you open your exam you'll see all the questions listed, with all the possible answers. Once you've worked out the correct answer just click the button next to it to set your choice.<br /> Once you've done that for all the questions, click the blue Submit button at the bottom and your exam will be submitted, and you'll be presented with your mark.</p>
    </div>
    <div class="black_border">
        <h1>Question: I'm a user and my question hasn't been answered here, how can I get more help?</h1>
        <p class="text">I'm sorry we haven't covered your issue here. Head over to our <a href="{%url 'exam_network:contact'%}">Contact</a> page and you can get in touch directly and we'll get your problem resolved. </p>
    </div>
</div>
{% endblock %}

templates/exam_network/two_split.html
{% extends "exam_network/base.html" %}
{% block page_content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'two_split/two_split.css' %}">
<div style="text-align: center;">
    <div id="signup_wrapper">
        <img src="{% block two_split_image_source%}{%endblock%}" alt="two split image" class="interactive">
        <div class="black_border">
            {% block two_split_content%}{%endblock%}
        </div>
    </div>
</div>
{% endblock %}